#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar  8 18:52:27 2019

@author: alem
"""

import numpy as np
import cv2
pic = np.zeros((500,500,3), dtype='uint8')
color=(255,0,255)
cv2.circle(pic, (250,250),50,color)
cv2.imshow('dark', pic)
cv2.waitKey(0)
cv2.destroyAllWindows()