#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  8 18:36:13 2019

@author: alem
"""
import numpy as np
import cv2
a=[1, 2, 3]
b=[4, 5, 6]
c=np.column_stack((a,b))
#Make c 3D

cv2.imwrite('color_img.jpg', c)


#-----------------------------------------------
img = np.zeros([5,5,3])

img[:,:,0] = numpy.ones([5,5])*64/255.0
img[:,:,1] = numpy.ones([5,5])*128/255.0
img[:,:,2] = numpy.ones([5,5])*192/255.0

cv2.imwrite('color_img.jpg', img)
cv2.imshow("image", img);
cv2.waitKey();